from core_data_modules.cleaners import Codes, somali
from dateutil.parser import isoparse
from src.pipeline_configuration_spec import *


PIPELINE_CONFIGURATION = PipelineConfiguration(
    pipeline_name="SDC Minority Inclusion",
    description="Minority Inclusion and Service Delivery Evaluation on SDC Projects in Somalia",
    engagement_database=EngagementDatabaseClientConfiguration(
        credentials_file_url="gs://avf-credentials/avf-engagement-databases-firebase-credentials-file.json",
        database_path="engagement_databases/IMAQAL-2"
    ),
    uuid_table=UUIDTableClientConfiguration(
        credentials_file_url="gs://avf-credentials/avf-id-infrastructure-firebase-adminsdk-6xps8-b9173f2bfd.json",
        table_name="avf-global-urn-to-participant-uuid",
        uuid_prefix="avf-participant-uuid-"
    ),
    operations_dashboard=OperationsDashboardConfiguration(
        credentials_file_url="gs://avf-credentials/avf-dashboards-firebase-adminsdk-gvecb-ef772e79b6.json"
    ),
    csv_sources=[
        #                                              Demogs
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-gender_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("gender")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-disability_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("disability")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-recently_displaced_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("recently_displaced")],
            timezone="Africa/Mogadishu"
        ),
        #                                              s01e01
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e01_RQA_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01e01")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e01_age_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("age")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e01_language_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("household_language")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e01_location_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("location")],
            timezone="Africa/Mogadishu"
        ),
        #                                               s01e02
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e02_RQA_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01e02")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e02_age_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("age")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e02_language_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("household_language")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e02_location_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("location")],
            timezone="Africa/Mogadishu"
        ),
        #                                               s01e03
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e03_RQA_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01e03")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e03_age_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("age")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e03_language_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("household_language")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e03_location_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("location")],
            timezone="Africa/Mogadishu"
        ),
        #                                               s01e04
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e04_RQA_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01e04")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e04_age_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("age")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e04_language_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("household_language")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e04_location_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("location")],
            timezone="Africa/Mogadishu"
        ),
        #                                               s01e05
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e05_RQA_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01e05")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e05_age_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("age")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e05_language_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("household_language")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e05_location_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("location")],
            timezone="Africa/Mogadishu"
        ),
        #                                               s01e06
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e06_RQA_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01e06")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e06_age_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("age")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e06_language_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("household_language")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01e06_location_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("location")],
            timezone="Africa/Mogadishu"
        ),
        #                                               Evaluation
        # ----------------------------------------------------------------------------------------------------
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01_eval_age_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("age")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01_eval_language_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("household_language")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01_eval_lessons_learnt_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01_eval_lessons_learnt")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01_eval_location_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("location")],
            timezone="Africa/Mogadishu"
        ),
        CSVSource(
            "gs://avf-project-datasets/2024/SDC-Minority-Inclusion/SDC-MI-s01_eval_suggestions_de_identified.csv",
            engagement_db_datasets=[CSVDatasetConfiguration("sdc_mi_s01_eval_suggestions")],
            timezone="Africa/Mogadishu"
        ),
    ],
    coda_sync=CodaConfiguration(
        coda=CodaClientConfiguration(credentials_file_url="gs://avf-credentials/coda-production.json"),
        sync_config=CodaSyncConfiguration(
            dataset_configurations=[
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01e01",
                    engagement_db_dataset="sdc_mi_s01e01",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01e01"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01e01"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01e02",
                    engagement_db_dataset="sdc_mi_s01e02",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01e02"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01e02"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01e03",
                    engagement_db_dataset="sdc_mi_s01e03",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01e03"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01e03"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01e04",
                    engagement_db_dataset="sdc_mi_s01e04",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01e04"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01e04"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01e05",
                    engagement_db_dataset="sdc_mi_s01e05",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01e05"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01e05"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01e06",
                    engagement_db_dataset="sdc_mi_s01e06",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01e06"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01e06"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01_eval_lessons_learnt",
                    engagement_db_dataset="sdc_mi_s01_eval_lessons_learnt",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01_eval_lessons_learnt"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01_eval_lessons_learnt"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="SDC_MI_s01_eval_suggestions",
                    engagement_db_dataset="sdc_mi_s01_eval_suggestions",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("rqas/sdc_mi_s01_eval_suggestions"),
                                                coda_code_schemes_count=3),
                    ],
                    ws_code_match_value="sdc_mi_s01_eval_suggestions"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="IMAQAL_age",
                    engagement_db_dataset="age",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/age"),
                                                auto_coder=lambda text: str(
                                                    somali.DemographicCleaner.clean_age_within_range(text))
                                                ),
                    ],
                    ws_code_match_value="age",
                    dataset_users_file_url="gs://avf-project-datasets/2022/IMAQAL-POOL/coda_users.json"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="IMAQAL_gender",
                    engagement_db_dataset="gender",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/gender"),
                                                auto_coder=somali.DemographicCleaner.clean_gender)
                    ],
                    ws_code_match_value="gender",
                    dataset_users_file_url="gs://avf-project-datasets/2022/IMAQAL-POOL/coda_users.json"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="IMAQAL_household_language",
                    engagement_db_dataset="household_language",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/household_language"), 
                                                coda_code_schemes_count=4, auto_coder=None)
                    ],
                    ws_code_match_value="household_language",
                    dataset_users_file_url="gs://avf-project-datasets/2022/IMAQAL-POOL/coda_users.json"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="IMAQAL_location",
                    engagement_db_dataset="location",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/mogadishu_sub_district"),
                                                auto_coder=somali.DemographicCleaner.clean_mogadishu_sub_district),
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/somalia_district"), auto_coder=lambda text:
                        somali.DemographicCleaner.clean_somalia_district(text)
                        if somali.DemographicCleaner.clean_mogadishu_sub_district == Codes.NOT_CODED else Codes.NOT_CODED),
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/somalia_region"), auto_coder=None),
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/somalia_state"), auto_coder=None),
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/somalia_zone"), auto_coder=None),
                    ],
                    ws_code_match_value="location",
                    dataset_users_file_url="gs://avf-project-datasets/2022/IMAQAL-POOL/coda_users.json"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="IMAQAL_recently_displaced",
                    engagement_db_dataset="recently_displaced",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/recently_displaced"),
                                                auto_coder=somali.DemographicCleaner.clean_yes_no)
                    ],
                    ws_code_match_value="recently_displaced",
                    dataset_users_file_url="gs://avf-project-datasets/2022/IMAQAL-POOL/coda_users.json"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="IMAQAL_disability",
                    engagement_db_dataset="disability",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/disability"),
                                                auto_coder=somali.DemographicCleaner.clean_yes_no)
                    ],
                    ws_code_match_value="disability",
                    dataset_users_file_url="gs://avf-project-datasets/2022/IMAQAL-POOL/coda_users.json"
                ),
                CodaDatasetConfiguration(
                    coda_dataset_id="IMAQAL_clan",
                    engagement_db_dataset="clan",
                    code_scheme_configurations=[
                        CodeSchemeConfiguration(code_scheme=load_code_scheme("demographics/clan"))
                    ],
                    ws_code_match_value="clan",
                    dataset_users_file_url="gs://avf-project-datasets/2022/IMAQAL-POOL/coda_users.json"
                ),
            ],
            ws_correct_dataset_code_scheme=load_code_scheme("ws_correct_dataset"),
            project_users_file_url="gs://avf-project-datasets/2023/SDC-Survey/coda_users.json",
        )
    ),
    archive_configuration=ArchiveConfiguration(
        archive_upload_bucket="gs://pipeline-execution-backup-archive",
        bucket_dir_path="2025/SDC-Minority-Inclusion"
    ),
    analysis=AnalysisConfiguration(
        google_drive_upload=GoogleDriveUploadConfiguration(
            credentials_file_url="gs://avf-credentials/pipeline-runner-service-acct-avf-data-core-64cc71459fe7.json",
            drive_dir="sdc_mi_analysis_outputs"
        ),
        dataset_configurations=[
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01e01"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01e01_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01e01"),
                        analysis_dataset="sdc_mi_s01e01"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01e02"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01e02_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01e02"),
                        analysis_dataset="sdc_mi_s01e02"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01e03"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01e03_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01e03"),
                        analysis_dataset="sdc_mi_s01e03"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01e04"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01e04_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01e04"),
                        analysis_dataset="sdc_mi_s01e04"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01e05"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01e05_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01e05"),
                        analysis_dataset="sdc_mi_s01e05"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01e06"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01e06_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01e06"),
                        analysis_dataset="sdc_mi_s01e06"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01_eval_lessons_learnt"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01_eval_lessons_learnt_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01_eval_lessons_learnt"),
                        analysis_dataset="sdc_mi_s01_eval_lessons_learnt"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["sdc_mi_s01_eval_suggestions"],
                dataset_type=DatasetTypes.RESEARCH_QUESTION_ANSWER,
                raw_dataset="sdc_mi_s01_eval_suggestions_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("rqas/sdc_mi_s01_eval_suggestions"),
                        analysis_dataset="sdc_mi_s01_eval_suggestions"
                    )
                ]
            ),
            OperatorDatasetConfiguration(
                raw_dataset="operator_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/imaqal_operator"),
                        analysis_dataset="operator",
                        analysis_location=AnalysisLocations.SOMALIA_OPERATOR
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["age"],
                dataset_type=DatasetTypes.DEMOGRAPHIC,
                raw_dataset="age_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/age"),
                        analysis_dataset="age"
                    ),
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/age_category"),
                        analysis_dataset="age_category",
                        age_category_config=AgeCategoryConfiguration(
                            age_analysis_dataset="age",
                            categories={
                                (10, 14): "10 to 14",
                                (15, 17): "15 to 17",
                                (18, 35): "18 to 35",
                                (36, 54): "36 to 54",
                                (55, 99): "55 to 99"
                            }
                        )
                    ),
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["gender"],
                dataset_type=DatasetTypes.DEMOGRAPHIC,
                raw_dataset="gender_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/gender"),
                        analysis_dataset="gender"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["location"],
                dataset_type=DatasetTypes.DEMOGRAPHIC,
                raw_dataset="location_raw",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/mogadishu_sub_district"),
                        analysis_dataset="mogadishu_sub_district",
                        analysis_location=AnalysisLocations.MOGADISHU_SUB_DISTRICT
                    ),
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/somalia_district"),
                        analysis_dataset="district",
                        analysis_location=AnalysisLocations.SOMALIA_DISTRICT
                    ),
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/somalia_region"),
                        analysis_dataset="region",
                        analysis_location=AnalysisLocations.SOMALIA_REGION
                    ),
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/somalia_state"),
                        analysis_dataset="state",
                        analysis_location=AnalysisLocations.SOMALIA_STATE
                    ),
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/somalia_zone"),
                        analysis_dataset="zone",
                        analysis_location=AnalysisLocations.SOMALIA_ZONE
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["recently_displaced"],
                dataset_type=DatasetTypes.DEMOGRAPHIC,
                raw_dataset="recently_displaced",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/recently_displaced"),
                        analysis_dataset="recently_displaced"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["disability"],
                dataset_type=DatasetTypes.DEMOGRAPHIC,
                raw_dataset="disability",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/disability"),
                        analysis_dataset="disability"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["household_language"],
                dataset_type=DatasetTypes.DEMOGRAPHIC,
                raw_dataset="household_language",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/household_language"),
                        analysis_dataset="household_language"
                    )
                ]
            ),
            AnalysisDatasetConfiguration(
                engagement_db_datasets=["clan"],
                dataset_type=DatasetTypes.DEMOGRAPHIC,
                raw_dataset="clan",
                coding_configs=[
                    CodingConfiguration(
                        code_scheme=load_code_scheme("demographics/clan"),
                        analysis_dataset="clan"
                    )
                ]
            ),
        ],
        ws_correct_dataset_code_scheme=load_code_scheme("ws_correct_dataset")
    )
)
